# numpy get started

导入numpy库，并查看numpy版本

In [1]:
import numpy as np

In [ ]:
1. 是什么
2. 能干啥
3. 怎么用
4. 有什么注意
5. 扩展。。。

## 一、创建ndarray

### 1. 使用np.array()由python list创建

In [6]:
data = np.array([1,2.0,'3',4,5,6])

In [7]:
display(data)

array(['1', '2.0', '3', '4', '5', '6'], dtype='<U32')

参数为列表：
[1, 4, 2, 5, 3]

注意：
- numpy默认ndarray的所有元素的类型是相同的
- 如果传进来的列表中包含不同的类型，则统一为同一类型，优先级：str>float>int

### 2. 使用np的routines函数创建

包含以下常见创建方法：

1) np.ones(shape, dtype=None, order='C')

In [15]:
data1 = np.ones(shape=(2,3),dtype=int)
data1

array([[1, 1, 1],
       [1, 1, 1]])

2) np.zeros(shape, dtype=float, order='C')

3) np.full(shape, fill_value, dtype=None, order='C')

In [16]:
np.full(shape=(5,5),fill_value=9,dtype=int)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

4) np.eye(N, M=None, k=0, dtype=float)  
对角线为1其他的位置为0

In [22]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

5) np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [26]:
np.linspace(1,100,num=100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

6) np.arange([start, ]stop, [step, ]dtype=None)

In [28]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

7) np.random.randint(low, high=None, size=None, dtype='l')

In [32]:
np.random.randint(0,100,size=50)

array([27, 35, 79, 82, 69, 56, 11, 52, 76, 11, 21, 17, 21, 59, 24, 95, 55,
       72, 79, 48, 57, 59, 26, 28, 17, 30, 38, 35, 11, 15, 36, 24,  7, 61,
       93, 91,  3, 43, 36, 35, 73, 49,  3, 33, 99, 10, 93, 25, 20, 19])

8) np.random.randn(d0, d1, ..., dn)  

标准正太分布　

np.random.normal()

In [51]:
np.random.randn(5,5)

array([[ 0.67048714,  0.75258725,  1.03909643, -0.19032789,  0.36798616],
       [-0.07090496, -0.21986101, -0.58450388, -0.02990081,  0.17152391],
       [ 0.63200074, -0.23933857,  0.51071846, -0.37265619,  0.92585424],
       [-0.14230658, -0.4363032 , -0.25131376,  1.4752428 ,  0.18895801],
       [-0.16423272, -0.51207357, -1.01738775, -0.97026906, -0.62137873]])

In [50]:
np.random.normal(10,1, 1000)

array([ 8.81818662, 10.06211632,  9.90735042,  7.85010873, 10.33377469,
       10.50902414,  8.72310358,  9.39743777, 11.1965065 ,  9.00060267,
        9.84753906,  9.52464562,  9.23136156,  9.96493262, 10.59815084,
       10.28475666,  8.60917897, 10.43803167, 11.52523239,  8.48234724,
        8.7699976 ,  8.86637311, 11.42427752, 11.14708768,  9.26475959,
       10.24205097,  9.4266755 , 11.35133332, 10.16355998, 10.95525003,
        9.07629253, 10.25678056, 11.31183963,  8.15970145, 10.57297388,
        9.02473965, 10.64542736, 10.70468593, 11.96207857,  9.77850181,
        9.04375649,  9.61759868,  9.46515655,  7.71336798,  8.73853265,
       12.58774606,  8.38232211, 12.31635741, 11.4562184 ,  9.64810359,
       10.69094483, 10.18799983, 10.16058477,  9.10422497,  9.81416524,
       10.19435798, 10.71024933,  8.8314469 , 10.4649335 , 10.08839799,
        9.01609527, 11.01127699, 10.74522756,  9.07833099,  9.49258456,
       11.64963062, 10.46169259,  9.80226113, 11.1509609 ,  9.55

9) np.random.random(size=None)  

生成0到1的随机数，左闭右开

In [54]:
data3 = np.random.random((1000,5))

## 二、ndarray的属性

4个必记参数：
ndim：维度
shape：形状（各维度的长度）
size：总长度

dtype：元素类型


In [55]:
data3.ndim

2

In [56]:
data3.shape

(1000, 5)

In [58]:
data3.size

5000

In [59]:
data3.dtype

dtype('float64')

## 三、ndarray的基本操作

### 1. 索引
一维与列表完全一致
多维时同理

In [62]:
data3[0,0]

0.5514481543776746

In [67]:
data4 = np.random.randint(0,100,20)
display(data4)

array([79, 11, 51, 67, 66, 64, 37, 92, 64, 65, 21, 14, 96, 52, 31, 24, 23,
       83, 26, 69])

In [66]:
data4[0]

73

In [69]:
data4[-1]

69

In [73]:
data4[[0,1]]

array([79, 11])

### 2. 切片
一维与列表完全一致
多维时同理

In [76]:
data4[0:2]

array([79, 11])

In [78]:
data3[0:2,0:2]

array([[0.55144815, 0.49413763],
       [0.22638148, 0.81081921]])

In [79]:
data4[::-1]

array([69, 26, 83, 23, 24, 31, 52, 96, 14, 21, 65, 64, 92, 37, 64, 66, 67,
       51, 11, 79])

In [80]:
data4[::2]

array([79, 51, 66, 37, 64, 21, 96, 31, 23, 26])

In [84]:
data3

array([[0.55144815, 0.49413763, 0.69539275, 0.54086528, 0.84890651],
       [0.22638148, 0.81081921, 0.04501155, 0.43571467, 0.37340599],
       [0.73640719, 0.90424944, 0.49725554, 0.22163888, 0.38162209],
       ...,
       [0.21565495, 0.3695381 , 0.78156366, 0.94229838, 0.7372538 ],
       [0.68346927, 0.00739582, 0.09188592, 0.53061822, 0.43843695],
       [0.60425886, 0.36014737, 0.63475305, 0.74729219, 0.16469087]])

In [85]:
data3[::-1,::-1]

array([[0.16469087, 0.74729219, 0.63475305, 0.36014737, 0.60425886],
       [0.43843695, 0.53061822, 0.09188592, 0.00739582, 0.68346927],
       [0.7372538 , 0.94229838, 0.78156366, 0.3695381 , 0.21565495],
       ...,
       [0.38162209, 0.22163888, 0.49725554, 0.90424944, 0.73640719],
       [0.37340599, 0.43571467, 0.04501155, 0.81081921, 0.22638148],
       [0.84890651, 0.54086528, 0.69539275, 0.49413763, 0.55144815]])

将数据反转，例如[1,2,3]---->[3,2,1]

两个：：进行切片

### 3. 变形
使用reshape函数，注意参数是一个tuple！

In [89]:
data4.reshape(-1,1)

array([[79],
       [11],
       [51],
       [67],
       [66],
       [64],
       [37],
       [92],
       [64],
       [65],
       [21],
       [14],
       [96],
       [52],
       [31],
       [24],
       [23],
       [83],
       [26],
       [69]])

In [91]:
data4.reshape(4,5)

array([[79, 11, 51, 67, 66],
       [64, 37, 92, 64, 65],
       [21, 14, 96, 52, 31],
       [24, 23, 83, 26, 69]])

### 4. 级联
1. np.concatenate()
级联需要注意的点：
- 级联的参数是列表：一定要加中括号或小括号
- 维度必须相同
- 形状相符
- 【重点】级联的方向默认是shape这个tuple的第一个值所代表的维度方向
- 可通过axis参数改变级联的方向

2. np.hstack与np.vstack  
水平级联与垂直级联,处理自己，进行维度的变更

### 5. 切分

与级联类似，三个函数完成切分工作：
- np.split
- np.vsplit
- np.hsplit

In [99]:
np.split(data4,indices_or_sections=(3,5),axis=0)

[array([79, 11, 51]),
 array([67, 66]),
 array([64, 37, 92, 64, 65, 21, 14, 96, 52, 31, 24, 23, 83, 26, 69])]

### 6. 副本
所有赋值运算不会为ndarray的任何元素创建副本。对赋值后的对象的操作也对原来的对象生效。

可使用copy()函数创建副本

## 四、ndarray的聚合操作

### 1. 求和np.sum

In [105]:
np.sum(data3,axis=0)

array([503.07387269, 503.2846459 , 497.03877434, 495.37565582,
       508.56712112])

In [107]:
np.max(data3)

0.9993530364300184

In [108]:
np.min(data3)

0.0002847743718157325

In [112]:
np.std(data3,axis=0)

array([0.28563659, 0.28643623, 0.28251817, 0.29078201, 0.28261875])

### 2. 最大最小值：np.max/ np.min
同理

any()  有True返回True


all()  有False返回False

In [133]:
arr = np.array([np.nan,1,2,3])

In [134]:
arr.any()

True

In [135]:
arr.all()

True

In [136]:
np.nansum(arr)

6.0

### 3. 其他聚合操作
    Function Name	NaN-safe Version	Description
    np.sum	np.nansum	Compute sum of elements
    np.prod	np.nanprod	Compute product of elements
    np.mean	np.nanmean	Compute mean of elements
    np.std	np.nanstd	Compute standard deviation
    np.var	np.nanvar	Compute variance
    np.min	np.nanmin	Find minimum value
    np.max	np.nanmax	Find maximum value
    np.argmin	np.nanargmin	Find index of minimum value
    np.argmax	np.nanargmax	Find index of maximum value
    np.median	np.nanmedian	Compute median of elements
    np.percentile	np.nanpercentile	Compute rank-based statistics of elements
    np.any	N/A	Evaluate whether any elements are true
    np.all	N/A	Evaluate whether all elements are true
    np.power 幂运算

np.sum 和 np.nansum 的区别
nan not a number

#### 操作文件

使用pandas打开文件president_heights.csv
获取文件中的数据

## 五、ndarray的矩阵操作

### 1. 基本矩阵操作

1) 算术运算符：
- 加减乘除

2) 矩阵积np.dot()

### 2. 广播机制

【重要】ndarray广播机制的两条规则
- 规则一：为缺失的维度补1
- 规则二：假定缺失元素用已有值填充


例1：
m = np.ones((2, 3))
a = np.arange(3)
求M+a

例2：
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
求a+b

习题
a = np.ones((4, 1))
b = np.arange(4)
求a+b

## 六、ndarray的排序

小测验：
使用以上所学numpy的知识，对一个ndarray对象进行冒泡排序。
def bubleSort(x):
代码越短越好

### 1. 快速排序
np.sort()与ndarray.sort()都可以，但有区别：
- np.sort()不改变输入
- ndarray.sort()本地处理，不占用空间，但改变输入

### 2. 部分排序
np.partition(a,k)

有的时候我们不是对全部数据感兴趣，我们可能只对最小或最大的一部分感兴趣。
- 当k为正时，我们想要得到最小的k个数
- 当k为负时，我们想要得到最大的k个数